### ISSUE TITLE
Microsoft BizSpark

### ISSUE THREAD

**Issue by kdpuvvadi** [victorfrye/microsoftgraveyard#80]
**Microsoft BizSpark**
Microsoft Bizspark or Bizspark One 

**Describe the product**
Microsoft program that provides support, Azure credits and free licenses to selected Microsoft products to software entrepreneurs and start ups including Office 265, MSDN(Microsoft Developper Network) Subscription for teams etc. providing the benefits and the perks to the selected members of this program for a term of 3 years.

**Initial release date of the product**
November of 2009 

**Discontinuation date of the product**
Feb 2018

**Relevant links**
- Original urls:- https://www.microsoft.com/bizspark/ https://bizspark.microsoft.com/
- Internet Archive:- https://web.archive.org/web/20090228042650/https://www.microsoft.com/bizspark/
- Before closing:- https://web.archive.org/web/20170930070352/https://bizspark.microsoft.com/

**Additional context**
After discountinung the program, They launched Microsoft for Startups. (https://www.microsoft.com/startups)

**Comment by victorfrye** [comment]
So... researching BizSpark, it appears it was just rebranded as Microsoft for Startups? Is there a particular nostalgia for BizSpark brand or a distinct offering that was killed along with the BizSpark brand for this program?

**Comment by InDieTasten** [comment]
As far as I understand, BizSpark was more of a discounted subscription offering than an actual product. It just gave you access to other actual products.

If that understanding is correct, I wouldn't personally add this to the list, as starting to list these types of offerings will quickly dilute the graveyard with temporal subscription offerings, rather than actual products that offered functionality, that was then lost by Microsoft discontinuing/killing it.

There are still plenty of ways to obtain other subscription to the same products that BizSpark provided.

My personal take. I guess BizSpark could be an exemption, because it has been offered for a long time and many businesses made use of this program.

**Comment by kdpuvvadi** [comment]
> If that understanding is correct, I wouldn't personally add this to the list, as starting to list these types of offerings will quickly dilute the graveyard with temporal subscription offerings, rather than actual products that offered functionality, that was then lost by Microsoft discontinuing/killing it.

Makes sense

**Comment by victorfrye** [comment]
I appreciate you all resolving this and agree. Adding BizSpark seems like it would open the door to other discount programs Microsoft offers in nonprofit, education, and healthcare industries for example rather than actual products. The Graveyard should primarily focus on the actual enterprise, developer, and/or consumer products of Microsoft rather than programs offering those programs.  A software equivalent would be Windows Essentials (a bundle of products) versus Windows Movie Maker and Windows Live Writer. 

Some exceptions may occur, but it seems we agree this is not a particular example.  Love the contribution to discussions though!
